/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: GiantPhysX.i

package GiantPhysXGo

/*
#cgo CXXFLAGS: -std=c++11
#cgo CFLAGS: -I .
#cgo LDFLAGS: -L ../bin -lGiantPhysXRelease_x64
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
extern void _wrap_Swig_free_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_GiantPhysXGo_27fd12e0c257ea6e(swig_intgo arg1);
extern uintptr_t _wrap_new_GxVec3__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(void);
extern uintptr_t _wrap_new_GxVec3__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(float arg1, float arg2, float arg3);
extern void _wrap_GxVec3_x_set_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, float arg2);
extern float _wrap_GxVec3_x_get_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxVec3_y_set_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, float arg2);
extern float _wrap_GxVec3_y_get_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxVec3_z_set_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, float arg2);
extern float _wrap_GxVec3_z_get_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_delete_GxVec3_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_delete_GxIGameObject_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern _Bool _wrap_GxIGameObject_GetActive_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIGameObject_SetActive_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, _Bool arg2);
extern swig_type_1 _wrap_GxIGameObject_GetName_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIGameObject_SetName_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, swig_type_2 arg2);
extern swig_intgo _wrap_GxIGameObject_GetMask_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIGameObject_SetMask_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_GxIGameObject_GetPosition_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIGameObject_SetPosition_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, float arg2, float arg3, float arg4);
extern _Bool _wrap_GxIGameObject_Raycast__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern _Bool _wrap_GxIGameObject_Raycast__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, swig_intgo arg5);
extern void _wrap_delete_GxIPhysics_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern uintptr_t _wrap_GxIPhysics_CreateScene__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, swig_type_3 arg2);
extern uintptr_t _wrap_GxIPhysics_CreateScene__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIPhysics_DestroyScene_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_GxIPhysics_GetMask_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, swig_type_4 arg2);
extern swig_intgo _wrap_GxIPhysics_GetFullMask_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_delete_GxIScene_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIScene_Update_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern uintptr_t _wrap_GxIScene_CreateGameObject__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, swig_type_5 arg2);
extern uintptr_t _wrap_GxIScene_CreateGameObject__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_GxIScene_DestroyGameObject_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_GxIScene_Raycast_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, float arg4, swig_intgo arg5);
extern uintptr_t _wrap_new_GxLayerMask__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(void);
extern uintptr_t _wrap_new_GxLayerMask__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(swig_intgo arg1);
extern void _wrap_GxLayerMask_value_set_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_GxLayerMask_value_get_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern void _wrap_delete_GxLayerMask_GiantPhysXGo_27fd12e0c257ea6e(uintptr_t arg1);
extern uintptr_t _wrap_GxCreatePhysics_GiantPhysXGo_27fd12e0c257ea6e(swig_type_6 arg1, swig_type_7 arg2);
extern void _wrap_GxDestroyPhysics_GiantPhysXGo_27fd12e0c257ea6e(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_GiantPhysXGo_27fd12e0c257ea6e(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const GX_WINDOWS int = 1

type SwigcptrGxVec3 uintptr

func (p SwigcptrGxVec3) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGxVec3) SwigIsGxVec3() {
}

func NewGxVec3__SWIG_0() (_swig_ret GxVec3) {
	var swig_r GxVec3
	swig_r = (GxVec3)(SwigcptrGxVec3(C._wrap_new_GxVec3__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e()))
	return swig_r
}

func NewGxVec3__SWIG_1(arg1 float32, arg2 float32, arg3 float32) (_swig_ret GxVec3) {
	var swig_r GxVec3
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (GxVec3)(SwigcptrGxVec3(C._wrap_new_GxVec3__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(C.float(_swig_i_0), C.float(_swig_i_1), C.float(_swig_i_2))))
	return swig_r
}

func NewGxVec3(a ...interface{}) GxVec3 {
	argc := len(a)
	if argc == 0 {
		return NewGxVec3__SWIG_0()
	}
	if argc == 3 {
		return NewGxVec3__SWIG_1(a[0].(float32), a[1].(float32), a[2].(float32))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrGxVec3) SetX(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxVec3_x_set_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrGxVec3) GetX() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_GxVec3_x_get_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrGxVec3) SetY(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxVec3_y_set_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrGxVec3) GetY() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_GxVec3_y_get_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrGxVec3) SetZ(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxVec3_z_set_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrGxVec3) GetZ() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_GxVec3_z_get_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteGxVec3(arg1 GxVec3) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_GxVec3_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

type GxVec3 interface {
	Swigcptr() uintptr
	SwigIsGxVec3()
	SetX(arg2 float32)
	GetX() (_swig_ret float32)
	SetY(arg2 float32)
	GetY() (_swig_ret float32)
	SetZ(arg2 float32)
	GetZ() (_swig_ret float32)
}

type SwigcptrGxIGameObject uintptr

func (p SwigcptrGxIGameObject) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGxIGameObject) SwigIsGxIGameObject() {
}

func DeleteGxIGameObject(arg1 GxIGameObject) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_GxIGameObject_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrGxIGameObject) GetActive() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_GxIGameObject_GetActive_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrGxIGameObject) SetActive(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxIGameObject_SetActive_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrGxIGameObject) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_GxIGameObject_GetName_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrGxIGameObject) SetName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxIGameObject_SetName_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrGxIGameObject) GetMask() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_GxIGameObject_GetMask_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrGxIGameObject) SetMask(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxIGameObject_SetMask_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrGxIGameObject) GetPosition() (_swig_ret GxVec3) {
	var swig_r GxVec3
	_swig_i_0 := arg1
	swig_r = (GxVec3)(SwigcptrGxVec3(C._wrap_GxIGameObject_GetPosition_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrGxIGameObject) SetPosition(arg2 float32, arg3 float32, arg4 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_GxIGameObject_SetPosition_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.float(_swig_i_1), C.float(_swig_i_2), C.float(_swig_i_3))
}

func (arg1 SwigcptrGxIGameObject) Raycast__SWIG_0(arg2 GxIGameObject, arg3 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_GxIGameObject_Raycast__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrGxIGameObject) Raycast__SWIG_1(arg2 GxVec3, arg3 GxIGameObject, arg4 GxVec3, arg5 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	swig_r = (bool)(C._wrap_GxIGameObject_Raycast__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func (p SwigcptrGxIGameObject) Raycast(a ...interface{}) bool {
	argc := len(a)
	if argc == 2 {
		return p.Raycast__SWIG_0(a[0].(GxIGameObject), a[1].(int))
	}
	if argc == 4 {
		return p.Raycast__SWIG_1(a[0].(GxVec3), a[1].(GxIGameObject), a[2].(GxVec3), a[3].(int))
	}
	panic("No match for overloaded function call")
}

type GxIGameObject interface {
	Swigcptr() uintptr
	SwigIsGxIGameObject()
	GetActive() (_swig_ret bool)
	SetActive(arg2 bool)
	GetName() (_swig_ret string)
	SetName(arg2 string)
	GetMask() (_swig_ret int)
	SetMask(arg2 int)
	GetPosition() (_swig_ret GxVec3)
	SetPosition(arg2 float32, arg3 float32, arg4 float32)
	Raycast(a ...interface{}) bool
}

type SwigcptrGxIPhysics uintptr

func (p SwigcptrGxIPhysics) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGxIPhysics) SwigIsGxIPhysics() {
}

func DeleteGxIPhysics(arg1 GxIPhysics) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_GxIPhysics_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrGxIPhysics) CreateScene__SWIG_0(arg2 string) (_swig_ret GxIScene) {
	var swig_r GxIScene
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (GxIScene)(SwigcptrGxIScene(C._wrap_GxIPhysics_CreateScene__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrGxIPhysics) CreateScene__SWIG_1() (_swig_ret GxIScene) {
	var swig_r GxIScene
	_swig_i_0 := arg1
	swig_r = (GxIScene)(SwigcptrGxIScene(C._wrap_GxIPhysics_CreateScene__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrGxIPhysics) CreateScene(a ...interface{}) GxIScene {
	argc := len(a)
	if argc == 0 {
		return p.CreateScene__SWIG_1()
	}
	if argc == 1 {
		return p.CreateScene__SWIG_0(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrGxIPhysics) DestroyScene(arg2 GxIScene) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_GxIPhysics_DestroyScene_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrGxIPhysics) GetMask(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_GxIPhysics_GetMask_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrGxIPhysics) GetFullMask() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_GxIPhysics_GetFullMask_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type GxIPhysics interface {
	Swigcptr() uintptr
	SwigIsGxIPhysics()
	CreateScene(a ...interface{}) GxIScene
	DestroyScene(arg2 GxIScene)
	GetMask(arg2 string) (_swig_ret int)
	GetFullMask() (_swig_ret int)
}

type SwigcptrGxIScene uintptr

func (p SwigcptrGxIScene) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGxIScene) SwigIsGxIScene() {
}

func DeleteGxIScene(arg1 GxIScene) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_GxIScene_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrGxIScene) Update() {
	_swig_i_0 := arg1
	C._wrap_GxIScene_Update_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrGxIScene) CreateGameObject__SWIG_0(arg2 string) (_swig_ret GxIGameObject) {
	var swig_r GxIGameObject
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (GxIGameObject)(SwigcptrGxIGameObject(C._wrap_GxIScene_CreateGameObject__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrGxIScene) CreateGameObject__SWIG_1() (_swig_ret GxIGameObject) {
	var swig_r GxIGameObject
	_swig_i_0 := arg1
	swig_r = (GxIGameObject)(SwigcptrGxIGameObject(C._wrap_GxIScene_CreateGameObject__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrGxIScene) CreateGameObject(a ...interface{}) GxIGameObject {
	argc := len(a)
	if argc == 0 {
		return p.CreateGameObject__SWIG_1()
	}
	if argc == 1 {
		return p.CreateGameObject__SWIG_0(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrGxIScene) DestroyGameObject(arg2 GxIGameObject) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_GxIScene_DestroyGameObject_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrGxIScene) Raycast(arg2 GxVec3, arg3 GxVec3, arg4 float32, arg5 int) (_swig_ret GxIGameObject) {
	var swig_r GxIGameObject
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (GxIGameObject)(SwigcptrGxIGameObject(C._wrap_GxIScene_Raycast_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.float(_swig_i_3), C.swig_intgo(_swig_i_4))))
	return swig_r
}

type GxIScene interface {
	Swigcptr() uintptr
	SwigIsGxIScene()
	Update()
	CreateGameObject(a ...interface{}) GxIGameObject
	DestroyGameObject(arg2 GxIGameObject)
	Raycast(arg2 GxVec3, arg3 GxVec3, arg4 float32, arg5 int) (_swig_ret GxIGameObject)
}

type SwigcptrGxLayerMask uintptr

func (p SwigcptrGxLayerMask) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGxLayerMask) SwigIsGxLayerMask() {
}

func NewGxLayerMask__SWIG_0() (_swig_ret GxLayerMask) {
	var swig_r GxLayerMask
	swig_r = (GxLayerMask)(SwigcptrGxLayerMask(C._wrap_new_GxLayerMask__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e()))
	return swig_r
}

func NewGxLayerMask__SWIG_1(arg1 int) (_swig_ret GxLayerMask) {
	var swig_r GxLayerMask
	_swig_i_0 := arg1
	swig_r = (GxLayerMask)(SwigcptrGxLayerMask(C._wrap_new_GxLayerMask__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func NewGxLayerMask(a ...interface{}) GxLayerMask {
	argc := len(a)
	if argc == 0 {
		return NewGxLayerMask__SWIG_0()
	}
	if argc == 1 {
		return NewGxLayerMask__SWIG_1(a[0].(int))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrGxLayerMask) SetValue(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_GxLayerMask_value_set_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrGxLayerMask) GetValue() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_GxLayerMask_value_get_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteGxLayerMask(arg1 GxLayerMask) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_GxLayerMask_GiantPhysXGo_27fd12e0c257ea6e(C.uintptr_t(_swig_i_0))
}

type GxLayerMask interface {
	Swigcptr() uintptr
	SwigIsGxLayerMask()
	SetValue(arg2 int)
	GetValue() (_swig_ret int)
}

func GxCreatePhysics(arg1 string, arg2 string) (_swig_ret GxIPhysics) {
	var swig_r GxIPhysics
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (GxIPhysics)(SwigcptrGxIPhysics(C._wrap_GxCreatePhysics_GiantPhysXGo_27fd12e0c257ea6e(*(*C.swig_type_6)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func GxDestroyPhysics() {
	C._wrap_GxDestroyPhysics_GiantPhysXGo_27fd12e0c257ea6e()
}
