/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: GiantPhysX.i

#define SWIGMODULE GiantPhysXGo

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "GiantPhysX/GxAPI.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_GiantPhysXGo_27fd12e0c257ea6e(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_GiantPhysXGo_27fd12e0c257ea6e(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


GiantPhysX::GxVec3 *_wrap_new_GxVec3__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e() {
  GiantPhysX::GxVec3 *result = 0 ;
  GiantPhysX::GxVec3 *_swig_go_result;
  
  
  result = (GiantPhysX::GxVec3 *)new GiantPhysX::GxVec3();
  *(GiantPhysX::GxVec3 **)&_swig_go_result = (GiantPhysX::GxVec3 *)result; 
  return _swig_go_result;
}


GiantPhysX::GxVec3 *_wrap_new_GxVec3__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(float _swig_go_0, float _swig_go_1, float _swig_go_2) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  GiantPhysX::GxVec3 *result = 0 ;
  GiantPhysX::GxVec3 *_swig_go_result;
  
  arg1 = (float)_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  result = (GiantPhysX::GxVec3 *)new GiantPhysX::GxVec3(arg1,arg2,arg3);
  *(GiantPhysX::GxVec3 **)&_swig_go_result = (GiantPhysX::GxVec3 *)result; 
  return _swig_go_result;
}


void _wrap_GxVec3_x_set_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0, float _swig_go_1) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  float arg2 ;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->x = arg2;
  
}


float _wrap_GxVec3_x_get_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  
  result = (float) ((arg1)->x);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_GxVec3_y_set_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0, float _swig_go_1) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  float arg2 ;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->y = arg2;
  
}


float _wrap_GxVec3_y_get_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  
  result = (float) ((arg1)->y);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_GxVec3_z_set_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0, float _swig_go_1) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  float arg2 ;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->z = arg2;
  
}


float _wrap_GxVec3_z_get_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  
  result = (float) ((arg1)->z);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_GxVec3_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxVec3 *_swig_go_0) {
  GiantPhysX::GxVec3 *arg1 = (GiantPhysX::GxVec3 *) 0 ;
  
  arg1 = *(GiantPhysX::GxVec3 **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_delete_GxIGameObject_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  delete arg1;
  
}


bool _wrap_GxIGameObject_GetActive_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  result = (bool)(arg1)->GetActive();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_GxIGameObject_SetActive_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0, bool _swig_go_1) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  bool arg2 ;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  (arg1)->SetActive(arg2);
  
}


_gostring_ _wrap_GxIGameObject_GetName_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  result = (char *)(arg1)->GetName();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_GxIGameObject_SetName_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0, _gostring_ _swig_go_1) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  (arg1)->SetName((char const *)arg2);
  
  free(arg2); 
}


intgo _wrap_GxIGameObject_GetMask_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  result = (int)(arg1)->GetMask();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_GxIGameObject_SetMask_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0, intgo _swig_go_1) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  int arg2 ;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  (arg1)->SetMask(arg2);
  
}


GiantPhysX::GxVec3 *_wrap_GxIGameObject_GetPosition_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  GiantPhysX::GxVec3 result;
  GiantPhysX::GxVec3 *_swig_go_result;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  result = (arg1)->GetPosition();
  *(GiantPhysX::GxVec3 **)&_swig_go_result = new GiantPhysX::GxVec3(result); 
  return _swig_go_result;
}


void _wrap_GxIGameObject_SetPosition_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0, float _swig_go_1, float _swig_go_2, float _swig_go_3) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  
  (arg1)->SetPosition(arg2,arg3,arg4);
  
}


bool _wrap_GxIGameObject_Raycast__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0, GiantPhysX::GxIGameObject *_swig_go_1, intgo _swig_go_2) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  GiantPhysX::GxIGameObject *arg2 = (GiantPhysX::GxIGameObject *) 0 ;
  int arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  arg2 = *(GiantPhysX::GxIGameObject **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (bool)(arg1)->Raycast(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_GxIGameObject_Raycast__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIGameObject *_swig_go_0, GiantPhysX::GxVec3 *_swig_go_1, GiantPhysX::GxIGameObject *_swig_go_2, GiantPhysX::GxVec3 *_swig_go_3, intgo _swig_go_4) {
  GiantPhysX::GxIGameObject *arg1 = (GiantPhysX::GxIGameObject *) 0 ;
  GiantPhysX::GxVec3 arg2 ;
  GiantPhysX::GxIGameObject *arg3 = (GiantPhysX::GxIGameObject *) 0 ;
  GiantPhysX::GxVec3 arg4 ;
  int arg5 ;
  GiantPhysX::GxVec3 *argp2 ;
  GiantPhysX::GxVec3 *argp4 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIGameObject **)&_swig_go_0; 
  
  argp2 = (GiantPhysX::GxVec3 *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null GiantPhysX::GxVec3");
  }
  arg2 = (GiantPhysX::GxVec3)*argp2;
  
  arg3 = *(GiantPhysX::GxIGameObject **)&_swig_go_2; 
  
  argp4 = (GiantPhysX::GxVec3 *)_swig_go_3;
  if (argp4 == NULL) {
    _swig_gopanic("Attempt to dereference null GiantPhysX::GxVec3");
  }
  arg4 = (GiantPhysX::GxVec3)*argp4;
  
  arg5 = (int)_swig_go_4; 
  
  result = (bool)(arg1)->Raycast(arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_GxIPhysics_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIPhysics *_swig_go_0) {
  GiantPhysX::GxIPhysics *arg1 = (GiantPhysX::GxIPhysics *) 0 ;
  
  arg1 = *(GiantPhysX::GxIPhysics **)&_swig_go_0; 
  
  delete arg1;
  
}


GiantPhysX::GxIScene *_wrap_GxIPhysics_CreateScene__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIPhysics *_swig_go_0, _gostring_ _swig_go_1) {
  GiantPhysX::GxIPhysics *arg1 = (GiantPhysX::GxIPhysics *) 0 ;
  char *arg2 = (char *) 0 ;
  GiantPhysX::GxIScene *result = 0 ;
  GiantPhysX::GxIScene *_swig_go_result;
  
  arg1 = *(GiantPhysX::GxIPhysics **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (GiantPhysX::GxIScene *)(arg1)->CreateScene((char const *)arg2);
  *(GiantPhysX::GxIScene **)&_swig_go_result = (GiantPhysX::GxIScene *)result; 
  free(arg2); 
  return _swig_go_result;
}


GiantPhysX::GxIScene *_wrap_GxIPhysics_CreateScene__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIPhysics *_swig_go_0) {
  GiantPhysX::GxIPhysics *arg1 = (GiantPhysX::GxIPhysics *) 0 ;
  GiantPhysX::GxIScene *result = 0 ;
  GiantPhysX::GxIScene *_swig_go_result;
  
  arg1 = *(GiantPhysX::GxIPhysics **)&_swig_go_0; 
  
  result = (GiantPhysX::GxIScene *)(arg1)->CreateScene();
  *(GiantPhysX::GxIScene **)&_swig_go_result = (GiantPhysX::GxIScene *)result; 
  return _swig_go_result;
}


void _wrap_GxIPhysics_DestroyScene_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIPhysics *_swig_go_0, GiantPhysX::GxIScene *_swig_go_1) {
  GiantPhysX::GxIPhysics *arg1 = (GiantPhysX::GxIPhysics *) 0 ;
  GiantPhysX::GxIScene *arg2 = (GiantPhysX::GxIScene *) 0 ;
  
  arg1 = *(GiantPhysX::GxIPhysics **)&_swig_go_0; 
  arg2 = *(GiantPhysX::GxIScene **)&_swig_go_1; 
  
  (arg1)->DestroyScene(arg2);
  
}


intgo _wrap_GxIPhysics_GetMask_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIPhysics *_swig_go_0, _gostring_ _swig_go_1) {
  GiantPhysX::GxIPhysics *arg1 = (GiantPhysX::GxIPhysics *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIPhysics **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)(arg1)->GetMask((char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_GxIPhysics_GetFullMask_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIPhysics *_swig_go_0) {
  GiantPhysX::GxIPhysics *arg1 = (GiantPhysX::GxIPhysics *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GiantPhysX::GxIPhysics **)&_swig_go_0; 
  
  result = (int)(arg1)->GetFullMask();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_GxIScene_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIScene *_swig_go_0) {
  GiantPhysX::GxIScene *arg1 = (GiantPhysX::GxIScene *) 0 ;
  
  arg1 = *(GiantPhysX::GxIScene **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_GxIScene_Update_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIScene *_swig_go_0) {
  GiantPhysX::GxIScene *arg1 = (GiantPhysX::GxIScene *) 0 ;
  
  arg1 = *(GiantPhysX::GxIScene **)&_swig_go_0; 
  
  (arg1)->Update();
  
}


GiantPhysX::GxIGameObject *_wrap_GxIScene_CreateGameObject__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIScene *_swig_go_0, _gostring_ _swig_go_1) {
  GiantPhysX::GxIScene *arg1 = (GiantPhysX::GxIScene *) 0 ;
  char *arg2 = (char *) 0 ;
  GiantPhysX::GxIGameObject *result = 0 ;
  GiantPhysX::GxIGameObject *_swig_go_result;
  
  arg1 = *(GiantPhysX::GxIScene **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (GiantPhysX::GxIGameObject *)(arg1)->CreateGameObject((char const *)arg2);
  *(GiantPhysX::GxIGameObject **)&_swig_go_result = (GiantPhysX::GxIGameObject *)result; 
  free(arg2); 
  return _swig_go_result;
}


GiantPhysX::GxIGameObject *_wrap_GxIScene_CreateGameObject__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIScene *_swig_go_0) {
  GiantPhysX::GxIScene *arg1 = (GiantPhysX::GxIScene *) 0 ;
  GiantPhysX::GxIGameObject *result = 0 ;
  GiantPhysX::GxIGameObject *_swig_go_result;
  
  arg1 = *(GiantPhysX::GxIScene **)&_swig_go_0; 
  
  result = (GiantPhysX::GxIGameObject *)(arg1)->CreateGameObject();
  *(GiantPhysX::GxIGameObject **)&_swig_go_result = (GiantPhysX::GxIGameObject *)result; 
  return _swig_go_result;
}


void _wrap_GxIScene_DestroyGameObject_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIScene *_swig_go_0, GiantPhysX::GxIGameObject *_swig_go_1) {
  GiantPhysX::GxIScene *arg1 = (GiantPhysX::GxIScene *) 0 ;
  GiantPhysX::GxIGameObject *arg2 = (GiantPhysX::GxIGameObject *) 0 ;
  
  arg1 = *(GiantPhysX::GxIScene **)&_swig_go_0; 
  arg2 = *(GiantPhysX::GxIGameObject **)&_swig_go_1; 
  
  (arg1)->DestroyGameObject(arg2);
  
}


GiantPhysX::GxIGameObject *_wrap_GxIScene_Raycast_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxIScene *_swig_go_0, GiantPhysX::GxVec3 *_swig_go_1, GiantPhysX::GxVec3 *_swig_go_2, float _swig_go_3, intgo _swig_go_4) {
  GiantPhysX::GxIScene *arg1 = (GiantPhysX::GxIScene *) 0 ;
  GiantPhysX::GxVec3 arg2 ;
  GiantPhysX::GxVec3 arg3 ;
  float arg4 ;
  int arg5 ;
  GiantPhysX::GxVec3 *argp2 ;
  GiantPhysX::GxVec3 *argp3 ;
  GiantPhysX::GxIGameObject *result = 0 ;
  GiantPhysX::GxIGameObject *_swig_go_result;
  
  arg1 = *(GiantPhysX::GxIScene **)&_swig_go_0; 
  
  argp2 = (GiantPhysX::GxVec3 *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null GiantPhysX::GxVec3");
  }
  arg2 = (GiantPhysX::GxVec3)*argp2;
  
  
  argp3 = (GiantPhysX::GxVec3 *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null GiantPhysX::GxVec3");
  }
  arg3 = (GiantPhysX::GxVec3)*argp3;
  
  arg4 = (float)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  result = (GiantPhysX::GxIGameObject *)(arg1)->Raycast(arg2,arg3,arg4,arg5);
  *(GiantPhysX::GxIGameObject **)&_swig_go_result = (GiantPhysX::GxIGameObject *)result; 
  return _swig_go_result;
}


GiantPhysX::GxLayerMask *_wrap_new_GxLayerMask__SWIG_0_GiantPhysXGo_27fd12e0c257ea6e() {
  GiantPhysX::GxLayerMask *result = 0 ;
  GiantPhysX::GxLayerMask *_swig_go_result;
  
  
  result = (GiantPhysX::GxLayerMask *)new GiantPhysX::GxLayerMask();
  *(GiantPhysX::GxLayerMask **)&_swig_go_result = (GiantPhysX::GxLayerMask *)result; 
  return _swig_go_result;
}


GiantPhysX::GxLayerMask *_wrap_new_GxLayerMask__SWIG_1_GiantPhysXGo_27fd12e0c257ea6e(intgo _swig_go_0) {
  int arg1 ;
  GiantPhysX::GxLayerMask *result = 0 ;
  GiantPhysX::GxLayerMask *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (GiantPhysX::GxLayerMask *)new GiantPhysX::GxLayerMask(arg1);
  *(GiantPhysX::GxLayerMask **)&_swig_go_result = (GiantPhysX::GxLayerMask *)result; 
  return _swig_go_result;
}


void _wrap_GxLayerMask_value_set_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxLayerMask *_swig_go_0, intgo _swig_go_1) {
  GiantPhysX::GxLayerMask *arg1 = (GiantPhysX::GxLayerMask *) 0 ;
  int arg2 ;
  
  arg1 = *(GiantPhysX::GxLayerMask **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->value = arg2;
  
}


intgo _wrap_GxLayerMask_value_get_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxLayerMask *_swig_go_0) {
  GiantPhysX::GxLayerMask *arg1 = (GiantPhysX::GxLayerMask *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GiantPhysX::GxLayerMask **)&_swig_go_0; 
  
  result = (int) ((arg1)->value);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_GxLayerMask_GiantPhysXGo_27fd12e0c257ea6e(GiantPhysX::GxLayerMask *_swig_go_0) {
  GiantPhysX::GxLayerMask *arg1 = (GiantPhysX::GxLayerMask *) 0 ;
  
  arg1 = *(GiantPhysX::GxLayerMask **)&_swig_go_0; 
  
  delete arg1;
  
}


GiantPhysX::GxIPhysics *_wrap_GxCreatePhysics_GiantPhysXGo_27fd12e0c257ea6e(_gostring_ _swig_go_0, _gostring_ _swig_go_1) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  GiantPhysX::GxIPhysics *result = 0 ;
  GiantPhysX::GxIPhysics *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (GiantPhysX::GxIPhysics *)GxCreatePhysics((char const *)arg1,(char const *)arg2);
  *(GiantPhysX::GxIPhysics **)&_swig_go_result = (GiantPhysX::GxIPhysics *)result; 
  free(arg1); 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_GxDestroyPhysics_GiantPhysXGo_27fd12e0c257ea6e() {
  GxDestroyPhysics();
  
}


#ifdef __cplusplus
}
#endif

